// Auto-generated by shadcn/ui init
// This utility function is used to merge Tailwind CSS classes

import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
